version: "3.8"

services:
  dev-player:
    container_name: sf-dev-player
    image: public-images-registry.cn-hangzhou.cr.aliyuncs.com/public/sf-ai-2023:judge
    volumes:
      - "./code:/code"
    working_dir: /code
    command: ["tail","-f", "/dev/null"]

  judge-web-debug:
    container_name: sf-dev-web-debug
    image: public-images-registry.cn-hangzhou.cr.aliyuncs.com/public/sf-ai-2023:web
    volumes:
      - .:/app
      - /app/judge-web/node_modules
    ports:
      - 3000:3000

networks:
  sf:
    name: sf
    internal: true
    external: true
