FROM node:16.14-alpine AS development
ENV NODE_ENV development
# Add a work directory
WORKDIR /app
# Copy files
COPY . .

WORKDIR /app/judge-web
RUN cd /app/judge-web && yarn
# Expose port
EXPOSE 3000
# Start the app
CMD [ "yarn", "dev" ]
