FROM ubuntu:latest
ENV BUILD_CACHE=3
RUN printf "deb https://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse 	\n\
deb-src https://mirrors.aliyun.com/ubuntu/ jammy main restricted universe multiverse 		\n\
												\n\
deb https://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse 	\n\
deb-src https://mirrors.aliyun.com/ubuntu/ jammy-security main restricted universe multiverse 	\n\
												\n\
deb https://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse 	\n\
deb-src https://mirrors.aliyun.com/ubuntu/ jammy-updates main restricted universe multiverse 	\n\
												\n\
deb https://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse 	\n\
deb-src https://mirrors.aliyun.com/ubuntu/ jammy-backports main restricted universe multiverse 	\n\
" > /etc/apt/sources.list
RUN sed -i 's/https:\/\/mirrors.aliyun.com/http:\/\/mirrors.cloud.aliyuncs.com/g' /etc/apt/sources.list
RUN ( uname -m | grep -q aarch64 ) && ( sed -i 's!/ubuntu/!/ubuntu-ports/!g' /etc/apt/sources.list ) || true 
RUN apt-get update -y
RUN apt-get install -y libcurl4-openssl-dev build-essential gdb curl vim golang # buildkit
RUN apt-get install -y python3 python3-pip nodejs 
RUN python3 -m pip install sanic requests schema asyncio networkx numpy pandas pip -i https://mirrors.aliyun.com/pypi/simple/
RUN apt-get install -y openjdk-8-jdk 
RUN apt-get install -y maven
RUN mkdir -p /root/.m2 && \
    echo "<settings><mirrors><mirror><id>alimaven</id><name>aliyun maven</name><url>http://maven.aliyun.com/nexus/content/groups/public/</url><mirrorOf>central</mirrorOf></mirror></mirrors></settings>" > /root/.m2/settings.xml



#RUN (cd /usr/lib/jvm/java-8-openjdk-amd64/ && ln -s /usr/lib/jvm/java-8-openjdk-amd64/ /usr/lib/jvm/java-8-openjdk) || (cd /usr/lib/jvm/java-8-openjdk-arm64/ && ln -s /usr/lib/jvm/java-8-openjdk-arm64/ /usr/lib/jvm/java-8-openjdk)
#ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk

RUN sed -i 's!http://mirrors.cloud.aliyuncs.com!https://mirrors.aliyun.com!g' /etc/apt/sources.list
